### ISSUE TITLE
Improve name check

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [Herdo/SSDTLifecycleExtension#14]
Affected version: 1.3.0

Description: The name of the DACPAC is now saved to a different location in the project file, namely `DacApplicationName`. This property should be evaluated as well.

Additional information:
- Evaluate `DacApplicationName` as primary source for the paths.
- Evaluate `SqlTargetname` as secondary source for the paths.
- Evaluate `Name` as the third source for the paths.

If the determined source for the paths doesn't match the SQL project name, write a warning message into the log output.

**Comment by Herdo** [comment]
`DacApplicationName` doesn't influence the DACPAC file name. Therefore, those changes are obsolete. Just adding the additional warning.
