### ISSUE TITLE
Post-deployment is not included

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [Herdo/SSDTLifecycleExtension#2]
Affected version: 1.1.0

Description: Post-deployment is not included in generated script.

Additional information:
Randomly affects script generation.

**Comment by Herdo** [comment]
Added validation for deployment script generation. If a generated script does not contain the defined pre- or post-deployment scripts, the generation is aborted. Further logging would be required to investigate the problem, but DacServices doesn't offer a logging option for DACPAC to DACPAC script generation.
