### ISSUE TITLE
Cannot create scripts

### ISSUE THREAD

**Issue by kjoebie** [Herdo/SSDTLifecycleExtension#24]
I installed this extension on VS 2019. Created a new SQL project. Scaffold the project as version 0.0.0.0. Add a table and saved it the project. Now when staring Script Creation again I still see the option of creating version 0.0.0.0. No changes are detected.

**Comment by Herdo** [comment]
@kjoebie The information is not enough to reproduce the issue. Do you have some more info for me? Is this a peristent error, or did it go away with restarting Visual Studio?

**Comment by kjoebie** [comment]
I restarted VS, de- and reinstalled your extension. But problem persists. When I change the Artifact path to something else (e.g. _Deployment1) and save the configuration file, I see a folder Properties and the file ssdtlifecycle.json are created. But after Script Creation no _Deployment1 folder is created. 

I'm using VS 2019 version 16.7.4 and .Net 4.8.03752 and SQL Data tools 16.0.62008.03130.

**Comment by Herdo** [comment]
@kjoebie Could you please copy/paste the complete log from the `SSDT Lifecycle` section in the `Output` window?

**Comment by kjoebie** [comment]
INFO: Initializing scaffolding ...
ERROR: Cannot read DacVersion of "C:\Users\Kjoebie\source\repos\NewDbVersion\NewDbVersion\NewDbVersion.sqlproj". Please make sure that the "DacVersion" is set correctly, e.g. "1.0.0". This value can bet set from your database project => "Properties" => "Project Settings" => "Output types" => "Data-tier Application" => "Properties..." => "Version".
INFO: ========== Scaffolding version  finished after 724 milliseconds. ==========

However, the properties are set like this:
![image](https://user-images.githubusercontent.com/7207207/94653358-bf08bd80-02fb-11eb-82a1-1aa43bf58f7a.png)

**Comment by Herdo** [comment]
That value there is just a display value provided by Visual Studio, not a value persisted in the sqlproj file.Just fill in a "1.0.0" and save the project. Then it'll work.

**Comment by kjoebie** [comment]
It's magic! Probably I overlooked this step in the docs. Thanks for the help.
