### ISSUE TITLE
DependencyResolver.GetViewModel resolves wrong view model

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [Herdo/SSDTLifecycleExtension#26]
When working with TFVC as source control provider, branches are manage on different paths.
Same projects, e.g. on a dev branch and release branch have the same name, but a different path.

When switching between the branches in the same Visual Studio instance, the previously opened project will still be used.

**Steps to reproduce:**

- Create sqlproj at `C:\Temp\Dev\MyDatabase.sqlproj`.
- Create sqlproj at `C:\Temp\Release\MyDatabase.sqlproj` as copy of `Dev`.
- Open script creation window for `Release` branch.
- Open `Dev` solution and open script creation window.

**Error:**
Even though the script creation window gets opened for the `Dev` branch, actions still happen on the `Release` branch.

**Comment by Herdo** [comment]
Resolved with update 1.3.5.
