### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [Herdo/SSDTLifecycleExtension#28]
The extension needs to be ported, so it can run as Visual Studio 2022 extension, as well as a Visual Studio 2019 extension.
See these upgrade guidelines: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by StefanOverHaevgRZ** [comment]
- [x] Update pipeline to latest `vmImage`
- [x] Upgrade `Microsoft.VSSDK.BuildTools` to version 17.* for VS2022 version
- [x] ~~Use `Microsoft.VisualStudio.Shell.Events.SoltutionEvents` for events instead of DTE2 SolutionEvents~~
- [x] Ensure `DTE2` is used all the way instead of plain `DTE` or `_DTE` class
- [x] Add `InstallationTarget` for 17.0 VS with `ProductArchitecture` of `amd64`
  - [x] InstallationTargets shouldn't be open ended (ever!), and have one entry for each version
- [x] Prerequisites should use open ended versions
- [x] Split extension **if incompatible dependencies exist**
  - [x] Rename source project to "2019"
  - [x] Move project to subdirectory for 2019
  - [x] Update path in solution
  - [x] ~~Update license path in csproj~~
  - [x] Add shared project
    - [x] Move windows, commands and package class into shared project
    - [x] Add reference to shared project to VS2019 project
  - [x] Copy 2019 folder as 2022 folder
    - [x] Rename csproj
    - [x] Change project guid
    - [x] Change product id guid
    - [x] ~~❓ Optional: [Create an Extension Pack](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthough-create-extension-pack?view=vs-2022)~~
  - [x] Add 2022 project to solution
  - [x] Change AssemblyNames and RootNamespaces
  - [x] Update package references to 17.*
  - [x] Change names in vsixmanifests
  - [x] Update InstallationTargets respectively
- [x] ~~❓ Optional: Use VSCT IntelliSense extension and include `VSGlobals.vsct`, update vsct file~~
- [x] Test package(s) 📑
- [x] Publish VSIX package(s) 🚀

**Comment by Herdo** [comment]
Implementation is done, builds are green and code analysis is working again.
